embed_assets: on

javascripts:
  task:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/namespace.js
    - public/javascripts/vendor/underscore-min.js
    - public/javascripts/vendor/backbone.js
    - public/javascripts/application.js
    - public/javascripts/models/Task.js
    - public/javascripts/collections/Tasks.js
    - public/javascripts/views/TasksView.js
    - public/javascripts/views/TaskView.js

stylesheets:
  task:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/task.css


